# fly.toml file generated for ghost-blog on 2021-03-27T11:26:02-05:00

app = "ghost-blog"

kill_signal = "SIGINT"
kill_timeout = 5

# [build]
# image = "ghost:4.1.2"

[env]
FLY_PRIMARY_REGION="ord"

[mount]
source = "ghost_content"
destination = "/var/lib/ghost/content"

[[services]]
  internal_port = 2368
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
